controller:
  name: controller
  ingressClass: nginx
  service:
    omitClusterIP: true
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
defaultBackend:
  service:
    omitClusterIP: true
sigsci:
  image:
    repository: signalsciences/sigsci-agent
    tag: latest
    pullPolicy: Always
  accessKeyId: accesskeyid
  secretAccessKey: secretaccesskey
  secret:
    name: sigsci-secret
    accessKeyId: __replace__
    secretAccessKey: __replace__