controller:
  name: controller
  ingressClass: nginx
  replicaCount: 1
  image:
    repository: signalsciences/sigsci-nginx-ingress-controller
    tag: 0.26.1
  service:
    omitClusterIP: true
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60
defaultBackend:
  service:
    omitClusterIP: true
sigsci:
  image:
    repository: signalsciences/sigsci-agent
    tag: latest
    pullPolicy: Always
  accessKeyId: accesskeyid
  secretAccessKey: secretaccesskey
  secret:
    name: sigsci-secret
    accessKeyId: __replace__
    secretAccessKey: __replace__