controller:
  deploySigSci: true
  extraVolumeMounts:
  - name: sigsci-tmp
    mountPath: /sigsci/tmp
  extraVolumes:
  - name: sigsci-tmp
    emptyDir: {}
  service:
    omitClusterIP: true
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
defaultBackend:
  service:
    omitClusterIP: true
sigsci:
  controller:
    name: sigsci-agent
    image:
      repository: signalsciences/sigsci-agent
      tag: latest
      pullPolicy: Always
    volumeMounts:
    - name: sigsci-tmp
      mountPath: /sigsci/tmp
    accessKeyId: accesskeyid
    secretAccessKey: secretaccesskey
  configMap:
    name: nginx-configuration
  secret:
    name: sigsci-secret
    accessKeyId: __replace__
    secretAccessKey: __replace__