# More info at:
# - https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-admins-namespace
  namespace: app1
subjects:
- kind: Group
  name: ab62a6c8-be51-4cf2-9fee-a88e351b08cf
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reads-cluster
subjects:
- kind: Group
  name: ab62a6c8-be51-4cf2-9fee-a88e351b08cf
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: creates-namespaces
subjects:
- kind: Group
  name: ab62a6c8-be51-4cf2-9fee-a88e351b08cf
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: namespace-creator
  apiGroup: rbac.authorization.k8s.io
---
