apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxweb
  namespace: app1
  labels:
    app: nginxweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxweb
  template:
    metadata:
      labels:
        app: nginxweb
    spec:
      containers:
        - name: nginxweb
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 80
              path: /
          livenessProbe:
            httpGet:
              port: 80
              path: /
          resources:
            requests:
              memory: 128Mi
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200"
---
apiVersion: v1
kind: Service
metadata:
  name: nginxweb
  namespace: app1
  labels:
    app: nginxweb
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginxweb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxweb-ingress
  namespace: app1
  annotations:
    kubernetes.io/ingress.class: nginx-app1
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginxweb
          servicePort: 80
