apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Values.sigsci.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  accesskeyid: {{ .Values.sigsci.secret.accessKeyId }}
  secretaccesskey: {{ .Values.sigsci.secret.secretAccessKey }}