apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ template "nginx-ingress.chart" . }}
    component: {{ .Values.controller.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.sigsci.secret.name }}
type: Opaque
data:
  accesskeyid: {{ .Values.sigsci.secret.accessKeyId }}
  secretaccesskey: {{ .Values.sigsci.secret.secretAccessKey }}