apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: tcp-services
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (toYaml .Values.tcp) . | indent 2 }}
