# More info at:
# - https://kubernetes.io/docs/concepts/policy/resource-quotas/
# - https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

apiVersion: v1
kind: Namespace
metadata:
  name: app2
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app2-resource-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "20"
    limits.memory: 70Gi
---
